[pytest]
markers =
    TC_1
    TC_2
    TC_3
    TC_4
    TC_5
    TC_6
    TC_7
    TC_8
    TC_9
    TC_10
    TC_11
    TC_12
    TC_13
    TC_14
    TC_15
    TC_16
    TC_17
    TC_18
    TC_19
    TC_20
    TC_21
    TC_22
    TC_23
    TC_24
    TC_25
    TC_26
    TC_27
    TC_28
    TC_29
    TC_30
    TC_31
    TC_32
    TC_33
    TC_34

filterwarnings =
    ignore:.*builtin type SwigPyPacked has no __module__ attribute.*:DeprecationWarning
    ignore:.*builtin type SwigPyObject has no __module__ attribute.*:DeprecationWarning
    ignore:.*builtin type swigvarlink has no __module__ attribute.*:DeprecationWarning
    ignore:.*style lookup by style_id is deprecated.*:UserWarning
